language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_install:
  - pear config-set preferred_state beta
  - if [[ `php -r 'echo version_compare(PHP_VERSION, "7.2.0") > 0?"1":"0";'` ]]; yes '' | pecl install apcu 2> /dev/null; fi

install:
  - if [[ `php -r 'echo version_compare(PHP_VERSION, "7.2.0") < 0?"1":"0";'` ]]; then composer update; fi
  - if [[ `php -r 'echo version_compare(PHP_VERSION, "7.2.0") > 0?"1":"0";'` ]]; then composer install; fi